### ISSUE TITLE
Unclear how to encourage batching

### ISSUE THREAD

**Issue by maedoc** [marius311/muse_inference#8]
Having read the paper, it was clear that the MAP estimates should be batched, but when looking at the examples, it's not clear to me if that's something that happens automagically by JAX or PyMC or the user should take care of it? Or should I just step through the JAX code and print shapes etc? Thanks in advance for any tips.

**Comment by marius311** [comment]
Yea, this is a good observation, some problems can probably benefit from batching the parallel MAP solves. On the Jax side, its kind of set up to do it here: https://github.com/marius311/muse_inference/blob/b2a29cd8f48bac6d5de954d3962f79dc83b8fccf/muse_inference/muse_inference.py#L306

(and similarly in get_J and get_H) so that you can set the keyword arg `pmap = jax.vmap`. Can you try that and see if it works for you? I think it might, but I don't remember entirely tbh. 

In theory you should also be able to set that to be `pmap = jax.pmap` but in practice that was triggering recompilation due to https://github.com/google/jax/discussions/11023, I started restructuring the code a bit to get around that but never finished. I can see if I can make more progress on it. 

On the PyMC side, I'm not familiar at all with how batching works, any advice appreciated!

**Comment by marius311** [comment]
Oops, or rather `pmap = lambda f, *args: jax.vmap(f)(*args)` I think.

**Comment by maedoc** [comment]
Thanks for the tips, I'll try it out.  I was just getting a Jax env setup esp. w/ GPU support.  Did you happen to notice if it's easier to get GPU batching done in Julia instead of Python?  (I had already been prototyping some C++/CUDA but if batching is easier in Julia then I'd try that too)

**Comment by marius311** [comment]
Julia doesn't have anything as easy as `jax.vmap` so I'd probably go Python if you think that's going to be important for your problem.

**Comment by maedoc** [comment]
thanks! I'll reopen the issue if I encounter further problems.
